### ISSUE TITLE
Event Box - Speed potion

### ISSUE THREAD

**Issue by MrGrohminet** [Apero-Online/apero#208]
Hola 
Sujet plutôt simple, l'item n'est accessible qu'avec la quête pickpocket je crois et c'est chiant et cher. Sachant que les AD sont disp dans les évent box ainsi que les poison bottles et les Blue pot je propose qu'on les rajoute. 

Par contre pour pas que ça soit broken un valeur random entre 1p et 5p ?

Ça rajoute aussi un choix dans la box et divise un poil mieux les loots car ça peut vite monter sur certains évents (pas celui là par ex 😅)

A dispo pour échanger !

**Comment by S0DA456** [comment]
plutot simple a farmer d'apres moi, je farm seul avec 3 comptes 3bottle a la minute environ (grand max 2min)
sachant qu'on peut etre plusieurs a reclamer 3 bottles en même temps en plus. Je farm facilement 50potz en 20min. Il y a des techniques interessante dans tous le jeu il ne faudrait pas tout cassé ( aqua bottle, cursed water,elemental scroll, glistenning coat, proof potions, +X food, karvo, etc...

mais ça casse surtout le business de la revente pour ceux qui se casse 'a minima' le cucul
Apres, l'acces a l'event box n'est pas broken donc apres tout...

ça reste un item niche pour les woe et homunculus
