### ISSUE TITLE
Enlarge weight

### ISSUE THREAD

**Issue by MrGrohminet** [Apero-Online/apero#286]
J'implémente et on voit comment ca se comporte.

Ajout d'un objet magique permttant d'augmenter le weight limit en lieu et place de l'autoloot (skill enlarge weight limit lvl 1 : gratuit, level 2 quête)
Mettez 1 pouce en l'air ou en bas, il y'a le slow mode donc pesez vos réponses / remarques

**Comment by Alzwgga** [comment]
Ça a déjà été implémenter ?

**Comment by MrGrohminet** [comment]
@Alzwgga prochaine release
