### ISSUE TITLE
Backstab - position check removed

### ISSUE THREAD

**Issue by MrGrohminet** [Apero-Online/apero#301]
J'ouvre le poste pour suggérer la modification du skill "BackStab" du Rogue/Stalker.
Mon idée est simplement d'utilisé le "BackStab" du renewal c'est a dire que le skill téléporte dans le dos de la cible plutôt que de lui faire dos obligatoirement car soyons franc le skill est chiant a placé en PvM et impossible en PvP

Cela peu donner de l'intérêt a certains objets comme la Krierg d'Eddga ou la suite de card de Thief
Et si ca peu aider les rares Stalker du serveur a faire autre chose que du Full Strip en WoE x)

**Comment by Varguen** [comment]
Ajouté au site
https://www.apero-online.fr/jeu/ajustements
