### ISSUE TITLE
Upgrade weapon

### ISSUE THREAD

**Issue by MrGrohminet** [Apero-Online/apero#355]
Yo, est ce que ca vaut le coup si j'ouvre un ticket pour pouvoir selectionner le skill de Upgrade Weapon  ? le ticket est fermé obligé de up sans securité au max du lvl qu'on a c'est pas tres secure https://irowiki.org/wiki/Upgrade_Weapon

**Comment by Varguen** [comment]
Ajouté au site section Ajustement classe merchant
https://www.apero-online.fr/jeu/ajustements
