### ISSUE TITLE
@register

### ISSUE THREAD

**Issue by MrGrohminet** [Apero-Online/apero#370]
J'avais pas trop participer pour la proposition d'annonce 1 minute avant les events qui a été mit en place, mais en lisant un peu les nouveautés de ce matin j'ai un pti truc qui est venu en tête.

Pas possible de faire en sorte de s'inscrire (soit via le npc présent en capi, soit via un petit @event /event) pour faire en sorte d'être TP automatiquement dans la zone event peu de temps(1min?) avant l'évent ?

J'sais pas si ça serait un truc intéressant à mettre, mais j'me suis dit why not

(inscription ouverte 10min avant chaque event)

**Comment by Varguen** [comment]
Ajouté au site section généralités
https://www.apero-online.fr/jeu/generalites
