### ISSUE TITLE
Twilight Alchemy III

### ISSUE THREAD

**Issue by MrGrohminet** [Apero-Online/apero#394]
Bonjour, serait il possible d'adapter le sort "Twilight Alchemy III" pour faire en sorte que ca crée 50 alcohol (au lieu de 100), 50 acid bottle et 50 grenade bottle ?

L'ayant a 100 alcohol en ce moment, ce fait craft la moitié des acid et grenade a la main donc ca serait sympa de régler ça si la communauté est d'accord.
Merci d'avoir lu

**Comment by Varguen** [comment]
Je rajoute un petit commentaire à ça
les Twilight pour crafter les red et les yellow potion ca avait été demandé ? parce que jsuis pas sur que ca soit très utilisé.
des skills pour faire Fire bottle, Acid bottle et Alcohol séparément ca aurait été pratique
