### ISSUE TITLE
Master acc exp bonus

### ISSUE THREAD

**Issue by MrGrohminet** [Apero-Online/apero#464]
Je pense que pour favoriser l'axe PVE du serveur et favoriser les teams XP (surtout pour les guildless) il serait bien de mettre en place un bonus xp par MASTER ACCOUNT dans la team ( +5/10% par Master account) un peu comme ça se faisait il y a une quinzaine d'année sur Karma RO, bien sur en évitant tout abus en n'appliquant pas le bonus sur MVP.

Le bonus team s'appliquerait donc à chaque master account présent sur la map et pas en autofollow !

Sachant que la majorité des teams se font en guilde ça pénalise une partie des joueurs et ça favorise l'utilisation de X DA ce qui dénature totalement l'aspect PVE du serveur sachant qu'on peut bien plus facilement up un char 99 en leech en moins de 2Jours contrairement aux teams qui certes sont amusantes et peuvent créer des liens mais qui n'xp pas très vite et qui de surcroît sont très très rares hormis pour l'hebdomadaire quand c'est des mots intéressants. 

A vos avis...

**Comment by MrGrohminet** [comment]
2 persos : +10%
3 persos : +20 %
4 persos : +30%
5 persos : +50%

**Comment by angela-hubner** [comment]
> 2 persos : +10% 3 persos : +20 % 4 persos : +30% 5 persos : +50%

Salut ! Le bonux XP fonctionne quand même s'il y a plusieurs persos d'un même master account mais pas en auto follow ? Ou c'est vraiment 1 perso par master account dans la partie pour que ça marche ?
